"""User-facing progress messages."""

FINDING_TICKER = "Finding matching U.S. tickers."
RESOLVING_COMPANY = "Checking company identity and SEC mapping."
COLLECTING_EVIDENCE = "Collecting earnings, SEC, news, and fallback evidence."
LOADING_MEMORY = "Reading prior approved report memory."
MEMORY_NOT_FOUND = "No prior approved report memory found."
MEMORY_FOUND = "Prior approved report memory found."
MEMORY_LOOKUP_FAILED = "Continuing without prior report memory because Mem0 lookup failed."
ASSEMBLING_EVIDENCE = "Assembling evidence pack and citations."
MINIMUM_EVIDENCE_MET = "Minimum evidence met; ready for analysis."
MINIMUM_EVIDENCE_FAILED = "Stopping before draft because minimum evidence was not met."
ANALYZING_NEWS = "Finding earnings-relevant news themes."
ANALYZING_DELTA = "Comparing against prior approved report memory."
SKIPPING_DELTA_NO_MEMORY = "Skipping delta comparison because no prior approved report memory was found."
ANALYZING_RISK = "Identifying earnings-relevant risks and watch items."
DRAFTING_BRIEF = "Drafting the cited earnings research brief."
REVIEWING_BRIEF = "Reviewing citations, warnings, schema, and safety boundaries."
ASSESSING_QUALITY = "Checking report quality before human review."
REPAIRING_CITATIONS = "Repairing section citation metadata before reviewer retry."
REVISING_BRIEF = "Revising the brief from reviewer feedback."
REVIEW_FAILED = "Reviewer found issues that need revision before approval."
WAITING_FOR_APPROVAL = "Waiting for approval before saving."
